#!/bin/bash

cpp_or_c() {
  if [[ -n "$1" ]]; then
    NEW_PROJECT_NAME=$1
  else
    read -p "Enter project name: " NEW_PROJECT_NAME
  fi

  SRC_DIR="$(cd "$(dirname "$0")" && pwd)/starters/c_based"
  DEST_DIR="${NEW_PROJECT_NAME}"

  if [ -d "$DEST_DIR" ]; then
    echo "Error: Directory ${NEW_PROJECT_NAME} already exists!"
    exit 1
  fi

  cp -r "$SRC_DIR" "$DEST_DIR"
  cd "$DEST_DIR" || exit

  if [[ $2 == 'cpp' ]]; then
    mv src/main.c src/main.cpp
    sed -i "s/C_FLAGS  /CXX_FLAGS/g" Makefile
    sed -i "s/(CC)/(CXX)/g" Makefile
    echo "  Compiler: g++" >>.clangd
  else
    echo "  Compiler: gcc" >>.clangd
  fi
  sed -i "s/<executable>/${NEW_PROJECT_NAME}/g" Makefile
  sed -i "s/EXT :=/EXT := $2/g" Makefile
  sed -i "s/<executable>/${NEW_PROJECT_NAME}/g" README.md
  sed -i "s/<executable>/${NEW_PROJECT_NAME}/g" .vscode/launch.json
}

gradle_project() {
  if ! command -v gradle &>/dev/null; then
    echo "Error: Gradle is not installed. Please install it before proceeding."
    exit 1
  fi

  # If Gradle is installed, initialize the project
  gradle init
}

case $1 in
"java")
  gradle_project
  ;;
"c++" | "cpp")
  cpp_or_c $2 cpp
  ;;
"c")
  cpp_or_c $2 c
  ;;
"t3")
  pnpm create t3-app@latest
  pnpm dlx shadcn@latest init -d
  pnpm dlx shadcn@latest add *
  ;;
*)
  echo "Unsuported project type."
  ;;
esac
